public/js/email-connector.js, public/mix-manifest.json, resources/js/connectors/email/send/component.vue, resources/js/connectors/email/send/index.js, resources/js/connectors/email/send/inspector.vue, src/PluginServiceProvider.php
Update email connector for modeler version 0.2.x
=> Update email connector for modeler version 0.2.x

src/PluginServiceProvider.php
Fix at the publishing assets in Provider class because to load the routes in console mode
=>  Fix at publishing assets

README.md, composer.json, package.json, routes/console.php, src/PluginServiceProvider.php
=> Update package names to spark

composer.json, src/Controllers/EmailController.php, src/Seeds/code/EmailSend.php
resolves #10 
Enable reading in the data model when sending mail through the script.
=> Email Variables

src/Controllers/EmailController.php, src/Jobs/SendEmail.php
resolves #15 
- Add job SendEmail
=> Horizon Monitoring Tagging

routes/console.php, src/Seeds/EmailSendSeeder.php
resolves #7 
- Register/remove screen type "Email"
require https://github.com/ProcessMaker/spark/pull/1766
=> Register 'EMAIL' screen type in spark

src/Seeds/EmailSendSeeder.php
- Add name package in run script seeder
=> Add name package in implementation

composer.json
=> Remove processmaker/spark dependency

public/js/email-connector.js, public/mix-manifest.json, resources/js/connectors/email/send/Notification.vue
Refactored Notifications.vue and fixed bugs
Fixes #59 
Fixes #54
=> Fix email notification settings in inspector

README.md, composer.json, public/js/email-connector.js, public/mix-manifest.json, resources/js/connectors/email/send/Notification.vue
RE: https://github.com/ProcessMaker/package-webentry/issues/20
Fixes #55 
Part of this was fixed in the webentry package. The other part needs this PR for the email connector package
=> Check for config.email_notifications and set it if it does not exist

routes/console.php, src/ScreenRenderer.php
Fixes #49
Also prompts for node path now
=> Do not ask for env vars if they are already set

src/Notifications.php
=> Send _request magic data variable with email notifications

composer.json
- Removes a problematic CSS inliner that was causing issues with the iOS mail client
- Screenshots from several clients are available here: [Screenshots.zip](https://github.com/ProcessMaker/connector-send-email/files/4732061/Screenshots.zip)
Closes #103.
=> Fix rendering issues with iOS mail client

composer.json, src/Assets/ScreensInEmailConnector.php, src/PluginServiceProvider.php
- Adds an export dependency manager to the package so that screen assets attached to email connector nodes will be exported and imported
- Registers export dependency manager with core
- Updates core version constraint
Fixes #99.
=> Export Email Connector screens

package-lock.json, public/js/processes/screen-builder/typeEmail.js.LICENSE.txt, public/mix-manifest.json, resources/js/processes/screen-builder/typeEmail.js
- Removes multicolumn control from Email screen types
- Updates screen-builder and vue-form-element dependencies
Closes #105.
=> Remove multicolumn from email screen types

composer.json, src/Jobs/SendEmail.php, src/ScreenRenderer.php, tests/ScriptRunners/MockRunner.php
=> Allow html type to be passed in when sending an email

public/js/email-connector.js, public/mix-manifest.json, resources/js/ssr/entry.js, resources/js/ssr/package-lock.json, resources/js/ssr/src/App.vue, resources/js/ssr/webpack.config.js
Needed for running `npm link` in  the `ssr` directory
Fixes #109
=> Add URL to JSDOM Settings

public/mix-manifest.json, resources/js/processes/screen-builder/FormHtmlEditorStatic.vue
Fixed https://processmaker.atlassian.net/browse/FOUR-1837
- Add validation scape html
=> Rich Text does not render HTML from a variable in an Email screen

src/Notifications.php
Resolves [https://processmaker.atlassian.net/browse/FOUR-2319](https://processmaker.atlassian.net/browse/FOUR-2319)
There were issues with expressions. Now Mustache is supported.
=> FOUR-2319: Expressions on Email notifications from tasks don't work

public/js/email-connector.js, public/mix-manifest.json
Part of https://processmaker.atlassian.net/browse/FOUR-1837
Needed to be rebuilt after html vars were added
=> Rebuild SSR so it uses html variables

src/Jobs/SendEmail.php
Fixes https://processmaker.atlassian.net/browse/FOUR-2531
Do not html escape special characters in the email subject
=> Do not escape html in the email subject

src/Assets/ScreensInEmailConnector.php
Fixes: https://processmaker.atlassian.net/browse/FOUR-2528
Requires: https://github.com/ProcessMaker/processmaker/pull/3580
This PR includes:
- Add a validation to check if the assigned screen is present in the imported file.
=> Add log message when imported file does not contain referenced screen
